const USERS_TYPES = {
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_REQUEST_SUCCESS: "GET_USERS_REQUEST_SUCCESS",
  CREATE_NEW_USER: "CREATE_NEW_USER",
  DELETE_USER: "DELETE_USER",
};

export default USERS_TYPES;
